"use strict";
/* LEGACY, base on linux if you want to maintain this ☠️ */
module.exports = {
  shortcutKeys: {
    "add-due-date": "Cmd+Shift+T",
    "add-my-day": "Cmd+K",
    "complete-todo": "Cmd+Shift+N",
    "delete-list": "Cmd+Shift+D",
    "delete-todo": "Cmd+D",
    "global-create-todo": "Cmd+Alt+C",
    "global-search-todo": "Cmd+Alt+F",
    "global-toggle-window": "Cmd+Alt+A",
    "hide-todo": "Cmd+Shift+H",
    important: "Cmd+I",
    "my-day": "Cmd+M",
    "new-list": "Cmd+L",
    "new-todo": "Cmd+N",
    planned: "Cmd+P",
    "rename-list": "Cmd+Y",
    "rename-todo": "Cmd+T",
    return: "Esc",
    "set-reminder": "Cmd+Shift+E",
    settings: "Cmd+,",
    "sign-out": "Cmd+Alt+Q",
    tasks: "Cmd+J",
    "toggle-black-mode": "Cmd+B",
    "toggle-dark-mode": "Cmd+H",
    "toggle-sepia-mode": "Cmd+G",
    "toggle-sidebar": "Cmd+O",
    exit: "Cmd+Q",
  },
  theme: {
    bgPrimary: "#282A36",
    bgPrimaryTransparent: "#282A3633",
    bgSecondary: "#333648",
    bgTertiary: "#303342",
    bgHover: "#3B3E51",
    bgHoverSecondary: "#474C68",
    bgHoverTertiary: "#222D6E",
    bgActive: "#333855",
    bgActiveSecondary: "#3F456B",
    bgActiveTertiary: "#2D366C",
    bgSeparator: "#44475A33",
    bgBorder: "#44475A33",
    bgScrollbar: "#44475A33",
    fontColorPrimary: "#CCCCCC",
    fontColorSecondary: "#F8F8F2",
    fontColorTertiary: "#FFFFFF",
    fontColorWarning: "#FF5555",
    fontColorBrand: "#007262",
    fontColorDisable: "#A19F9D",
    red: "#FF5555",
    blue: "#288BE1",
    skyblue: "#8BE9FD",
    purple: "#BD93F9",
    green: "#50FA7B",
  },
};
