"use strict";
/* LEGACY, base on linux if you want to maintain this ☠️ */
module.exports = {
  shortcutKeys: {
    "add-due-date": "Cmd+Shift+T",
    "add-my-day": "Cmd+K",
    "complete-todo": "Cmd+Shift+N",
    "set-repeat": "Cmd+Shift+U",
    "delete-list": "Cmd+Shift+D",
    "delete-todo": "Cmd+D",
    "global-create-todo": "Cmd+Alt+C",
    "global-search-todo": "Cmd+Alt+F",
    "global-toggle-window": "Cmd+Alt+A",
    "hide-todo": "Cmd+Shift+H",
    important: "Cmd+I",
    "my-day": "Cmd+M",
    "new-list": "Cmd+L",
    "new-todo": "Cmd+N",
    planned: "Cmd+P",
    "rename-list": "Cmd+Y",
    "rename-todo": "Cmd+T",
    return: "Esc",
    "set-reminder": "Cmd+Shift+E",
    settings: "Cmd+,",
    "sign-out": "Cmd+Alt+Q",
    tasks: "Cmd+J",
    "toggle-dark-mode": "Cmd+H",
    "toggle-sidebar": "Cmd+B",
    exit: "Cmd+Q",
  },
  theme: {
    bgPrimary: "",
    bgPrimaryTransparent: "",
    bgSecondary: "",
    bgTertiary: "",
    bgHover: "",
    bgHoverSecondary: "",
    bgHoverTertiary: "",
    bgActive: "",
    bgActiveSecondary: "",
    bgBrand: "#007262",
    bgBrandHover: "#1e9484",
    bgBrandHoverSecondary: "#004c52",
    bgBrandSecondary: "#004c52",
    bgBrandDisable: "#303f40 ",
    bgActiveTertiary: "",
    bgSeparator: "",
    bgBorder: "",
    bgScrollbar: "",
    fontColorPrimary: "",
    fontColorSecondary: "",
    fontColorTertiary: "",
    fontColorWarning: "",
    fontColorBrand: "",
    fontColorDisable: "",
    red: "#f35863",
    blue: "#4a7dfd",
    skyblue: "#3cb9e9",
    purple: "#7a45bf",
    green: "#6ec35d",
  },
};
