"use strict";

module.exports = {
  shortcutKeys: {
    "add-due-date": "Ctrl+Shift+T",
    "set-reminder": "Ctrl+Shift+E",
    "set-repeat": "Ctrl+Shift+U",
    "add-my-day": "Ctrl+K",
    "complete-todo": "Ctrl+Shift+N",
    "delete-list": "Ctrl+Shift+D",
    "delete-todo": "Ctrl+D",
    "global-create-todo": "Ctrl+Alt+C",
    "global-search-todo": "Ctrl+Alt+F",
    "global-toggle-window": "Ctrl+Alt+A",
    "hide-todo": "Ctrl+Shift+H",
    important: "Ctrl+I",
    "my-day": "Ctrl+M",
    "new-list": "Ctrl+L",
    "new-todo": "Ctrl+N",
    planned: "Ctrl+P",
    "rename-list": "Ctrl+Y",
    "rename-todo": "Ctrl+T",
    return: "Esc",
    settings: "Ctrl+,",
    "sign-out": "Ctrl+Alt+Q",
    tasks: "Ctrl+J",
    "toggle-dark-mode": "Ctrl+H",
    "toggle-custom-mode": "Ctrl+S",
    "toggle-sidebar": "Ctrl+B",
    exit: "Ctrl+Q",
  },
  theme: {
    bgPrimary: "#121212",
    bgPrimaryTransparent: "#12121233",
    bgSecondary: "#1F1F1F",
    bgTertiary: "#111",
    bgHover: "#1F1F1F",
    bgHoverSecondary: "#131313",
    bgHoverTertiary: "#333333",
    bgActive: "#232323",
    bgActiveSecondary: "#333333",
    bgActiveTertiary: "#343434",
    bgSeparator: "#333333",
    bgBorder: "#222222",
    bgScrollbar: "#FFFFFF",
    fontColorPrimary: "#CCCCCC",
    fontColorSecondary: "#DDDDDD",
    fontColorTertiary: "#797775",
    fontColorWarning: "#A80000",
    fontColorBrand: "#007262",
    fontColorDisable: "#A19F9D",
    bgBrand: "#007262",
    bgBrandHover: "#1e9484",
    bgBrandHoverSecondary: "#004c52",
    bgBrandSecondary: "#004c52",
    bgBrandDisable: "#303f40 ",
    red: "#f35863",
    blue: "#4a7dfd",
    skyblue: "#3cb9e9",
    purple: "#7a45bf",
    green: "#6ec35d",
  },
};
