"use strict";
/* LEGACY, base on linux if you want to maintain this ☠️ */
module.exports = {
  shortcutKeys: {
    "add-due-date": "Ctrl+Shift+T",
    "add-my-day": "Ctrl+K",
    "complete-todo": "Ctrl+Shift+N",
    "delete-list": "Ctrl+Shift+D",
    "delete-todo": "Ctrl+D",
    "global-create-todo": "Ctrl+Alt+C",
    "global-search-todo": "Ctrl+Alt+F",
    "global-toggle-window": "Ctrl+Alt+A",
    "hide-todo": "Ctrl+Shift+H",
    important: "Ctrl+I",
    "my-day": "Ctrl+M",
    "new-list": "Ctrl+L",
    "new-todo": "Ctrl+N",
    planned: "Ctrl+P",
    "rename-list": "Ctrl+Y",
    "rename-todo": "Ctrl+T",
    return: "Esc",
    "set-reminder": "Ctrl+Shift+E",
    settings: "Ctrl+,",
    "sign-out": "Ctrl+Alt+Q",
    tasks: "Ctrl+J",
    "toggle-dark-mode": "Ctrl+B",
    "toggle-sidebar": "Ctrl+O",
    exit: "Ctrl+Q",
  },
  theme: {
    bgPrimary: "",
    bgPrimaryTransparent: "",
    bgSecondary: "",
    bgTertiary: "",
    bgHover: "",
    bgHoverSecondary: "",
    bgHoverTertiary: "",
    bgActive: "",
    bgActiveSecondary: "",
    bgBrand: "#007262",
    bgBrandHover: "#1e9484",
    bgBrandHoverSecondary: "#004c52",
    bgBrandSecondary: "#004c52",
    bgBrandDisable: "#303f40 ",
    bgActiveTertiary: "",
    bgSeparator: "",
    bgBorder: "",
    bgScrollbar: "",
    fontColorPrimary: "",
    fontColorSecondary: "",
    fontColorTertiary: "",
    fontColorWarning: "",
    fontColorBrand: "",
    fontColorDisable: "",
    red: "#f35863",
    blue: "#4a7dfd",
    skyblue: "#3cb9e9",
    purple: "#7a45bf",
    green: "#6ec35d",
  },
};
