"use strict";
/* LEGACY, base on linux if you want to maintain this ☠️ */
module.exports = {
  shortcutKeys: {
    "add-due-date": "Ctrl+Shift+T",
    "add-my-day": "Ctrl+K",
    "complete-todo": "Ctrl+Shift+N",
    "delete-list": "Ctrl+Shift+D",
    "delete-todo": "Ctrl+D",
    "global-create-todo": "Ctrl+Alt+C",
    "global-search-todo": "Ctrl+Alt+F",
    "global-toggle-window": "Ctrl+Alt+A",
    "hide-todo": "Ctrl+Shift+H",
    important: "Ctrl+I",
    "my-day": "Ctrl+M",
    "new-list": "Ctrl+L",
    "new-todo": "Ctrl+N",
    planned: "Ctrl+P",
    "rename-list": "Ctrl+Y",
    "rename-todo": "Ctrl+T",
    return: "Esc",
    "set-reminder": "Ctrl+Shift+E",
    settings: "Ctrl+,",
    "sign-out": "Ctrl+Alt+Q",
    tasks: "Ctrl+J",
    "toggle-black-mode": "Ctrl+B",
    "toggle-dark-mode": "Ctrl+H",
    "toggle-sepia-mode": "Ctrl+G",
    "toggle-sidebar": "Ctrl+O",
    exit: "Ctrl+Q",
  },
  theme: {
    bgPrimary: "#282A36",
    bgPrimaryTransparent: "#282A3633",
    bgSecondary: "#333648",
    bgTertiary: "#303342",
    bgHover: "#3B3E51",
    bgHoverSecondary: "#474C68",
    bgHoverTertiary: "#222D6E",
    bgActive: "#333855",
    bgActiveSecondary: "#3F456B",
    bgActiveTertiary: "#2D366C",
    bgSeparator: "#44475A33",
    bgBorder: "#44475A33",
    bgScrollbar: "#44475A33",
    fontColorPrimary: "#CCCCCC",
    fontColorSecondary: "#F8F8F2",
    fontColorTertiary: "#FFFFFF",
    fontColorWarning: "#FF5555",
    fontColorBrand: "#007262",
    fontColorDisable: "#A19F9D",
    red: "#FF5555",
    blue: "#288BE1",
    skyblue: "#8BE9FD",
    purple: "#BD93F9",
    green: "#50FA7B",
  },
};
